export const productColumn = [
  // { key: 'name', label: 'Ad Account', order: 1 },
  // { key: 'advertiser_id', label: 'Account ID', order: 2 },
  // { key: 'company', label: 'Business Center', order: 3 },
  // { key: 'display_timezone', label: 'Time Zone', order: 4 },
  // { key: 'status', label: 'Status', order: 5 },
  // { key: 'total_cost', label: 'Total Cost', order: 6 },
  // { key: 'clicks', label: 'Clicks', order: 7 },
  // { key: 'conversions', label: 'Conversions', order: 8 },
  // { key: 'cpa', label: 'CPA', order: 9 },
  // { key: 'cpm', label: 'CPM', order: 10 },
  // { key: 'conversion_rate', label: 'CVR (%)', order: 11 },
  // {
  //   key: 'cpc',
  //   label: 'CPC',
  //   order: 12,
  // },
  // { key: 'ctr', label: 'CTR (%)', order: 13 },
  // { key: 'impressions', label: 'Impressions', order: 14 },
  // { key: 'revenue', label: 'Revenue', order: 15 },
  // { key: 'roi', label: 'ROI (%)', order: 16 },
  // { key: 'profit', label: 'Profit', order: 17 },
  { key: 'name', label: 'Ad Account', order: 1 },
  { key: 'total_cost', label: 'Total Cost', order: 6 },
  { key: 'clicks', label: 'Clicks', order: 7 },
  { key: 'conversion_rate', label: 'CVR (%)', order: 11 },
  { key: 'cpa', label: 'CPA', order: 9 },
  { key: 'profit', label: 'Profit', order: 15 },
  { key: 'revenue', label: 'Revenue', order: 17 },
];
export const productFilterValue = [
  { key: 'name', label: 'Ad Account', order: 1 },
  { key: 'total_cost', label: 'Total Cost', order: 6 },
  { key: 'clicks', label: 'Clicks', order: 7 },
  { key: 'conversion_rate', label: 'CVR (%)', order: 11 },
  { key: 'cpa', label: 'CPA', order: 9 },
  { key: 'profit', label: 'Profit', order: 15 },
  { key: 'revenue', label: 'Revenue', order: 17 },
];
export const mediaBuyerColumn = [
  { key: 'name', label: 'Name', order: 1 },
  { key: 'total_cost', label: 'Total Cost', order: 2 },
  { key: 'clicks', label: 'Clicks', order: 3 },
  // {
  //   key: 'conversions',
  //   label: 'Conversions',
  //   order: 4,
  // },
  { key: 'cpa', label: 'CPA', order: 5 },
  // { key: 'cpm', label: 'CPM', order: 6 },
  { key: 'conversion_rate', label: 'CVR (%)', order: 7 },
  // {
  //   key: 'cpc',
  //   label: 'CPC',
  //   order: 8,
  // },
  // { key: 'ctr', label: 'CTR (%)', order: 9 },
  // { key: 'impressions', label: 'Impressions', order: 10 },
  { key: 'revenue', label: 'Revenue', order: 11 },
  // { key: 'roi', label: 'ROI (%)', order: 12 },
  { key: 'profit', label: 'Profit', order: 13 },
];
export const verticalsColumn = [
  { key: 'name', label: 'Name', order: 1 },
  { key: 'total_cost', label: 'Total Cost', order: 2 },
  { key: 'clicks', label: 'Clicks', order: 3 },
  // {
  //   key: 'conversions',
  //   label: 'Conversions',
  //   order: 4,
  // },
  { key: 'cpa', label: 'CPA', order: 5 },
  // { key: 'cpm', label: 'CPM', order: 6 },
  { key: 'conversion_rate', label: 'CVR (%)', order: 7 },
  // {
  //   key: 'cpc',
  //   label: 'CPC',
  //   order: 8,
  // },
  // { key: 'ctr', label: 'CTR (%)', order: 9 },
  // { key: 'impressions', label: 'Impressions', order: 10 },
  { key: 'revenue', label: 'Revenue', order: 11 },
  // { key: 'roi', label: 'ROI (%)', order: 12 },
  { key: 'profit', label: 'Profit', order: 13 },
];
export const mediaBuyerFilterValue = [
  { key: 'name', label: 'Name', order: 1 },
  { key: 'total_cost', label: 'Total Cost', order: 2 },
  { key: 'clicks', label: 'Clicks', order: 3 },
  { key: 'conversion_rate', label: 'CVR (%)', order: 11 },
  { key: 'cpa', label: 'CPA', order: 5 },
  { key: 'cpm', label: 'CPM', order: 6 },
  { key: 'conversion_rate', label: 'CVR (%)', order: 7 },
];
export const verticalsFilterValue = [
  { key: 'name', label: 'Name', order: 1 },
  { key: 'total_cost', label: 'Total Cost', order: 2 },
  { key: 'clicks', label: 'Clicks', order: 3 },
  { key: 'conversion_rate', label: 'CVR (%)', order: 11 },
  { key: 'cpa', label: 'CPA', order: 5 },
  { key: 'cpm', label: 'CPM', order: 6 },
  { key: 'conversion_rate', label: 'CVR (%)', order: 7 },
];
